server:
  port: ${port:${server_port:0}}
spring:
  data:
    mongodb:
      database: dbCreditAccount
      port: 27017
      host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
info:
  app:
    name: Spring Boot Actuator Api Credit Account
    web: '*'
  hello: Hi here!
logging:
  level:
    root: info
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}