server:
  port: 8081
spring:
  data:
    mongodb:
      database: dbClientBank
      port: 27017
      host: localhost
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
info:
  app:
    name: Spring Boot Actuator Api Client Bank
    web: '*'
  hello: Hi here!
logging:
  level:
    root: info
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8080/eureka
    instance:
      hostname: localhost